# Adapted from https://raw.githubusercontent.com/go-rod/rod/main/.github/workflows/docker.yml

name: Release docker image

on: [push, pull_request]

permissions:
  packages: write

jobs:
  docker-amd:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v3

      - run: go run ./cmd/build-docker/main.go $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}

  docker-arm:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - uses: docker/setup-qemu-action@v2

      - uses: actions/checkout@v3

      - run: go run ./cmd/build-docker/main.go $GITHUB_REF
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
          ARCH: arm